name: Jekyll Build - Deploy

permissions: write-all

on:
  push:
    branches:
    - main

jobs: 
  publish-website: 
    runs-on: ubuntu-latest
    steps:
    - name: install checkout v2
      uses: actions/checkout@v2
      with:
        ref: main
    - name: 🧪 Build and deploy
      uses: victoriadrake/jekyll-cd@master
