name: Jekyll Build - Deploy

on:
  push:
    branches:
    - main

jobs: 
  publish-website: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: main
    - name: Run with dest path
      uses: helaili/jekyll-build@v2
      with:
        target_branch: gh-pages
        target_path: /
        keep_history: true
        token: ${{ secrets.MY_GITHUB_KEY }}
