name: Jekyll Build - Deploy

on:
  push:
    branches:
    - main

jobs: 
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Building a jekyll site from configured directory, maybe deploying it.
        env: 
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_KEY }}
          GITHUB_REPOSITORY: ${{ secrets.MY_REPOSITORY }}
          GITHUB_ACTOR: ${{ secrets.MY_ACTOR }}
          JEKYLL_ROOT: "./"
          REMOTE_BRANCH: "gh-pages"
        uses: agentd00nut/jekyll-build-optional-deploy-gh-pages@master
